export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER__FAILURE';

export const INIT_HOME_SUCCESS = 'INIT_HOME_SUCCESS';


export const SOME_HOME_ONE = 'SOME_HOME_ONE';
export const SOME_HOME_TWO = 'SOME_HOME_TWO';
export const SOME_HOME_THREE = 'SOME_HOME_THREE';

export const SOME_EXAM_TOTAL_ONE = 'SOME_EXAM_TOTAL_ONE';
export const SOME_EXAM_TOTAL_TWO = 'SOME_EXAM_TOTAL_TWO';
export const SOME_EXAM_TOTAL_THREE = 'SOME_EXAM_TOTAL_THREE';

export const SOME_EXAM_ANALYSIS_ONE = 'SOME_EXAM_ANALYSIS_ONE';
export const SOME_EXAM_ANALYSIS_TWO = 'SOME_EXAM_ANALYSIS_TWO';
export const SOME_EXAM_ANALYSIS_THREE = 'SOME_EXAM_ANALYSIS_THREE';
